# Configuration file for Snakemake workflow in local machine
#snakemake --configfile snakemake/config_local.yaml --cores 10
env: "stenv"
output_dir: "output"
home_dir: "/Users/yangcheng/clear_bd/Balmer-Decrement-CLEAR"

num_threads: 10

paths:
    master_catalog_raw: "catalogs/master_cat_raw.fits"
    master_catalog_clean: "catalogs/master_cat.fits"
    master_catalog_auto_sel: "catalogs/master_cat_auto_sel.fits"
    plt_dir: "plots"
    data_products_dir: "data_products"
    psf_dir: "data_psf"
    line_extraction_dir: "data_extracted"
    radial_profiles_dir: "data_radial_profiles"

gen_master_catalog:
    reload: False
    test_length: 20 #num of object for test run, set to -1 for full run

download_data:
    data_products:
     - "full"
     - "beams"

psf_ha:
    wavelength: 656.461  # in nm
    psf_shape: 31  # in pixels
    save_individual_psf: False
    exist_skip: True

psf_hb:
    wavelength: 486.133  # in nm
    psf_shape: 31  # in pixels
    save_individual_psf: False
    exist_skip: True

psf_match:
    window: "CosineBellWindow"
    alpha: 0.97
    beta: 0.9


line_extraction:
    window_size: 100  # in pixels
    exist_skip: False


radial_profiles:
    annuli_width: 1